"""PLCopen TC6 XML V2.01 exporter (E3S2T1).

Serializes a validated ``PLC_AST`` into a PLCopen TC6 XML 2.01 document: minimal
standard header metadata (``fileHeader`` / ``contentHeader``), the POU
interface ``localVars`` populated from AST devices (sanitized names, ``BOOL``
types), and the POU body ``<ST>`` containing the deterministic Structured Text
logic with traceability comments generated by ``src.st_gen``.

Uses only the Python standard library (``xml.etree.ElementTree``). The document
targets the published TC6 v2.01 schema namespace
``http://www.plcopen.org/xml/tc6_0201``.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

from src.ast_schemas import PLC_AST
from src.st_gen import build_st_program, render_st_program, sanitize_var_name


PLCOPEN_NS = "http://www.plcopen.org/xml/tc6_0201"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
PLCOPEN_XSD = "http://www.plcopen.org/xml/tc6_0201_v2.01.xsd"

DEFAULT_XML_DIR = Path("data/plc/xml")

_P = f"{{{PLCOPEN_NS}}}"


def _q(tag: str) -> str:
    return f"{_P}{tag}"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _build_xml(ast: PLC_AST, program_name: str, st_code: str) -> ET.Element:
    """Assemble the PLCopen project element (namespace-aware)."""
    ET.register_namespace("", PLCOPEN_NS)
    ET.register_namespace("xsi", XSI_NS)

    root = ET.Element(
        _q("project"),
        attrib={f"{{{XSI_NS}}}schemaLocation": f"{PLCOPEN_NS} {PLCOPEN_XSD}"},
    )

    ET.SubElement(
        root,
        _q("fileHeader"),
        attrib={
            "companyName": "AutoPLC-Agent",
            "productName": "AutoPLC-Agent",
            "productVersion": "0.1.0",
            "creationDateTime": _now_iso(),
        },
    )
    content = ET.SubElement(
        root,
        _q("contentHeader"),
        attrib={
            "name": program_name,
            "modificationDateTime": _now_iso(),
        },
    )
    coord = ET.SubElement(content, _q("coordinateInfo"))
    for lang in ("fbd", "ld", "sfc", "st"):
        ET.SubElement(coord, _q(lang))

    types_el = ET.SubElement(root, _q("types"))
    pous = ET.SubElement(types_el, _q("pous"))
    pou = ET.SubElement(pous, _q("pou"), attrib={"name": program_name, "pouType": "program"})

    interface = ET.SubElement(pou, _q("interface"))
    local_vars = ET.SubElement(interface, _q("localVars"))
    for device in ast.devices:
        var = ET.SubElement(
            local_vars,
            _q("variable"),
            attrib={"name": sanitize_var_name(device.name) or "DEV"},
        )
        var_type = ET.SubElement(var, _q("type"))
        ET.SubElement(var_type, _q("BOOL"))

    body = ET.SubElement(pou, _q("body"))
    st_el = ET.SubElement(body, _q("ST"))
    st_el.text = "\n" + st_code + "\n"

    instances = ET.SubElement(root, _q("instances"))
    ET.SubElement(instances, _q("configurations"))
    return root


def export_ast_to_plcopen_xml(
    ast_path: Path | str, output_path: Path | str | None = None
) -> Path:
    """Export a single ``PLC_AST`` JSON to a PLCopen TC6 XML file.

    Returns the path of the written XML.
    """
    ast_path = Path(ast_path)
    ast = PLC_AST.model_validate_json(ast_path.read_text(encoding="utf-8"))

    program = build_st_program(ast, ast_path, ast_path.stem)
    st_code = render_st_program(program)

    if output_path is None:
        DEFAULT_XML_DIR.mkdir(parents=True, exist_ok=True)
        output_path = DEFAULT_XML_DIR / f"{ast_path.stem}.xml"
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    root = _build_xml(ast, program.program_name, st_code)
    tree = ET.ElementTree(root)
    tree.write(out, encoding="utf-8", xml_declaration=True)
    return out


def export_all_asts(output_dir: Path | str | None = None) -> list[Path]:
    """Batch-convert every ``data/ast/*.json`` into PLCopen XML.

    Returns the list of written XML paths.
    """
    out_dir = Path(output_dir) if output_dir else DEFAULT_XML_DIR
    results: list[Path] = []
    from src.ast_schemas import PLC_AST  # noqa: F401  (sig)

    for ast_path in sorted(Path("data/ast").glob("*.json")):
        results.append(export_ast_to_plcopen_xml(ast_path, out_dir / f"{ast_path.stem}.xml"))
    return results


if __name__ == "__main__":  # pragma: no cover
    for path in export_all_asts():
        print(f"wrote {path}")
